server:
  port: 8082
  servlet.context-path: /blog
  
spring:
  application:
    name: farm-blog-admin
  cloud:
    refresh:
      refreshable: none      
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null  
  datasource:
    url: jdbc:mysql://localhost:3306/ag_blog?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idel: 10
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: MyHikariCP
      max-lifetime: 1800000
      read-only: false
      connection-time: 30000
      connection-test-query: select 1
      
eureka:
  instance:
  # 项目配置有 server.servlet.context-path 属性，想要被 spring boot admin 监控，就要配置
    metadata-map:
      management:
        context-path: ${server.servlet.context-path}/actuator      
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
        # docker 部署开启  https://blog.csdn.net/clementad/article/details/70613209
    prefer-ip-address: true
    ip-address: 127.0.0.1
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/   
        
hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000
            
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  security:
    enabled: false                
    
mybatis:
    basepackage: com.kexin.farm.admin.mapper
    xmlLocation: classpath:mapper/**/*.xml
    mapper-locations: "classpath*:mapper/*.xml"
    
    
swagger2:
  base-package: com.farm.blog.admin
  title: 博客后台API接口文档
  description: Springboot利用swagger构建api文档
  terms-of-service-url: NO terms of service
  version: 1.0
  contact:
    name: yunnet
    url: https://spring.io
    email: dev@ke-xin.com.cn
  license: The Apache License, Version 2.0
  license-url: http://www.apache.org/licenses/LICENSE-2.0.html   
  
logging:
  level:
    tk.mybatis: DEBUG
    com.kexin.blog.admin: DEBUG  
