spring:
  application:
    name: farm-blog-ui
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    
server:
  port: 9700
  
eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
        # docker 部署开启  https://blog.csdn.net/clementad/article/details/70613209
    prefer-ip-address: true
    ip-address: 127.0.0.1
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/   
        
hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000
            
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  security:
    enabled: false         