server:
  port: 8764
  
spring:
  application:
    name: farm-monitor
  boot:
    admin:
      notify.mail:
        enabled: false
        to: 123@qq.com
        from: admin@qq.com
        ignore-changes:
          -
            "*:UP"   #从任何状态到up状态都不要发邮件通知
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: turbine
      client:
        url: http://localhost:8764
        instance:
          service-base-url: http://localhost:8764
          
  
eureka:
  instance:
    preferIpAddress: true
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
  client:
    healthcheck: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS      